config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:show]
  resources :weeks, only: [:show, :index]

  get '/', to: 'weeks#index'

  post '/pick', to: 'picks#create'

  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :picks
  has_many :users, through: :picks

  def self.between(away_team_name, home_team_name, kickoff_time = nil)
    kickoff_time ||= Time.zone.parse('12:00pm')

    create(home_team_id: Team.find_or_create_by(name: home_team_name).id,
           away_team_id: Team.find_or_create_by(name: away_team_name).id,
           kickoff_time: kickoff_time)
  end

  def home_team
    Team.find(home_team_id)
  end

  def away_team
    Team.find(away_team_id)
  end

  def finish(home_score, away_score)
    update_attributes(home_team_score: home_score, away_team_score: away_score)
  end

  def winner
    if finished?
      if home_team_score > away_team_score
        home_team
      else
        away_team
      end
    end
  end

  private

  def finished?
    home_team_score
  end
end

app/models/pick.rb
class Pick < ActiveRecord::Base
  belongs_to :game
  belongs_to :user

  def team
    if is_home_team
      home_team
    else
      away_team
    end
  end

  def other_team
    if is_home_team
      away_team
    else
      home_team
    end
  end

  def to_s
    "#{user.name} picks #{team.name} over #{other_team.name}"
  end

  def abbreviation(game_id)
    first_n_letters(game_id).capitalize
  end

  def home_team
    Team.find(game.home_team_id)
  end

  def away_team
    Team.find(game.away_team_id)
  end

  def correct?
    # TODO this doesn't handle tie games...
    home_score = game.home_team_score
    away_score = game.away_team_score

    if home_score && away_score
      if is_home_team
        home_score > away_score
      else
        away_score > home_score
      end
    end
  end

  private

  def first_n_letters(game_id)
    if team.name == '49ers'
      '49'
    else
      game = Game.find(game_id)
      last_letter = shared_letters(game.home_team.name, game.away_team.name)

      team.name[0..last_letter]
    end
  end

  def shared_letters(home, away, count=0)
    if home[0].downcase == away[0].downcase
      shared_letters(home[1..-1], away[1..-1], count + 1)
    else
      count
    end
  end
end

app/models/stat.rb
class Stat < ActiveRecord::Base
  belongs_to :user
  belongs_to :week

  def self.create_all_for_week(week)
    last_week = find_previous_week(week)
    if last_week
      last_week_game_ids = last_week.games.map(&:id)
      last_week_picks = Pick.where(game_id: last_week_game_ids)

      User.all.each do |user|
        stat = new(week_id: week.id, user_id: user.id)

        wins_last_week = last_week_picks.select { |pick| pick.user == user && pick.correct? }.length

        stat.games_won_last_week = wins_last_week
        stat.save!
      end

      set_standings(week)
    else
      User.all.each do |user|
        create(week_id: week.id, user_id: user.id, games_won_last_week: 0, current_standing: 1)
      end
    end
  end

  private

  def self.find_previous_week(week)
    # TODO this won't work for week 1
    Week.find_by(week_number: week.week_number - 1, year: week.year)
  end

  def self.set_standings(week)
    stats_by_games_won = where(week_id: week.id).order(:games_won_last_week)

    stats_by_games_won.each_with_index do |stat, index|
      stat.update_attributes(current_standing: User.count - index)
      stat.save!
    end
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  def record
    if ties > 0
      "#{wins} - #{losses} - #{ties}"
    else
      "#{wins} - #{losses}"
    end
  end

  def self.[](name)
    team = find_by_name(name)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :picks
  has_many :games, through: :picks

  def self.by_standing_in_week(week_id)
    stats = Stat.where(week_id: week_id)
    user_ids = stats.sort_by(&:current_standing).map(&:user_id)

    user_ids.map {|id| find_by(id: id)}.compact
  end

  def pick_abbreviation_for(game_id)
    if games.map(&:id).include?(game_id)
      pick = picks.find_by(game_id: game_id)
      pick.abbreviation(game_id)
    else
      ''
    end
  end
end

app/models/week.rb
class Week < ActiveRecord::Base
  has_many :games

  def games_by_kickoff_time
    games.order(:kickoff_time).all
  end

  def users_by_standing
    User.by_standing_in_week(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  def create
    params.each do |k, v|
      next unless k =~ /game\d*/

      is_home_team = v[0..3] == 'home'
      game = Game.find(k[4..-1].to_i)
      Pick.create(game_id: game.id,
                  is_home_team: is_home_team,
                  user_id: User.find_by(name: session[:current_user_name]).id)
    end

    redirect_to :back
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    session[:current_user_name] = params[:login_name]
    flash.now[:success] = 'logged in!'
    render 'new'
  end

  def destroy
    session[:current_user_name] = nil
    render 'new'
  end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  def index
    @weeks = Week.all
  end

  def show
    week = Week.find(params[:id])
    @week = week
    @users = @week.users_by_standing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.new(name: 'default_user')
  end

  def current_user_name
    @current_user.name if @current_user
  end

  def current_user=(user)
    @current_user = user
  end
end

app/views/games/show.html.erb
<h1>Games#show</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FootballPool</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <%= flash[:success] %>
  <%= flash[:error] %>
  <p>signed in as <%= session[:current_user_name] %></p>
  <body>
    <div class="body-container">

      <%= yield %>

    </div>
      <%= @current_user %>
    <div>
    </div>
  </body>

  <div>
    <p>params</p><br />
    <%= params.map {|k,v| [k,v]} %>
    <p>week id</p><br />
    <%= @week.try(:id) %>
    <p>session</p><br />
    <%= session.to_hash.map {|k,v| [k,v]} %>
  </div>
</html>

app/views/weeks/_picks_table.html.erb
<form action="/pick" method="POST">

<table>
  <tr>
    <th></th>
    <% @users.each do |user| %>
      <th class="user_names">
        <%= "***\n" if (session[:current_user_name] == user.name) %>
        <%= user.name %>
        <%= Stat.find_by(user_id: user.id, week_id: @week.id).try(:games_won_last_week) %>
        <%= "\n***" if (session[:current_user_name] == user.name) %>
      </th>
    <% end %>
  </tr>

  <% @week.games_by_kickoff_time.each do |game| %>
    <tr>
      <td class="team_names">
        <span class="away_team_name"><input type="radio" value="away<%= game.id %>" name="game<%= game.id %>"><%= game.away_team.name %></span>
        <span class="home_team_name"><input type="radio" value="home<%= game.id %>" name="game<%= game.id %>"><%= game.home_team.name %></span>
        <span class="vs">vs.</span>
      </td>

      <% @users.each do |user| %>
        <td class="pick_abbrev"><%= user.pick_abbreviation_for(game.id) %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<input type="submit">
</form>

app/views/weeks/_stats_table.html.erb
<table>
  <tr>
    <th></th>
    <% @users.each do |user| %>
      <th class="user_names">
        <%= "***" if (session[:current_user_name] == user.name) %>
        <%= user.name %>
        <%= "***" if (session[:current_user_name] == user.name) %>
      </th>
    <% end %>
  </tr>

  <% Stat.where(week_id: @week.id).each do |stat| %>
    <tr>
      <%= stat.current_standing %>
    </tr>
  <% end %>
</table>

app/views/weeks/_table.html.erb
<form action="/pick" method="POST">

<table>
  <tr>
    <th></th>
    <% User.all.each do |user| %>
      <th class="user_names">
        <%= "***\n" if (session[:current_user_name] == user.name) %>
        <%= user.name %>
        <%= "\n***" if (session[:current_user_name] == user.name) %>
      </th>
    <% end %>
  </tr>

  <% @week.games_in_order.each do |game| %>
    <tr>
      <td class="team_names">
        <span class="away_team_name"><input type="radio" value="away<%= game.id %>" name="game<%= game.id %>"><%= game.away_team.name %></span>
        <span class="home_team_name"><input type="radio" value="home<%= game.id %>" name="game<%= game.id %>"><%= game.home_team.name %></span>
        <span class="vs">vs.</span>
      </td>

      <% User.all.each do |user| %>
        <td class="pick_abbrev"><%= user.pick_abbreviation_for(game.id) %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<input type="submit">
</form>

app/views/weeks/index.html.erb
<h2>2014 Season</h2>
<h4>Regular Season</h4>

<% @weeks.each do |week| %>
  <%= link_to "Week #{week.week_number}", week_path(week.id) %>
<% end %>

<h4>Playoffs</h4>
<p>TBD</p>

app/views/weeks/show.html.erb
<h1>Week <%= @week.week_number %></h1>

<%= render "weeks/picks_table" %>
<%= render "weeks/stats_table" %>